In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

dataset = [['Milk', 'Cola', 'Cookie', 'Bread', 'Jam'],
           ['Ramen', 'Kimchi', 'Rice'],
           ['Ramen', 'Snack', 'Bread', 'Jam'],
           ['Rice', 'Kimchi'],
           ['Cola', 'Bear'],
           ['Cola', 'Cookie', 'Bread'],
           ['Milk', 'Bread', 'Jam'],
           ['Ramen', 'Cheese', 'Ham'],
           ['Bear', 'Snack', 'Cheese', 'Cookie'],
           ['Cookie', 'Bread', 'Jam', 'Snack']]

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,Bear,Bread,Cheese,Cola,Cookie,Ham,Jam,Kimchi,Milk,Ramen,Rice,Snack
0,False,True,False,True,True,False,True,False,True,False,False,False
1,False,False,False,False,False,False,False,True,False,True,True,False
2,False,True,False,False,False,False,True,False,False,True,False,True
3,False,False,False,False,False,False,False,True,False,False,True,False
4,True,False,False,True,False,False,False,False,False,False,False,False
5,False,True,False,True,True,False,False,False,False,False,False,False
6,False,True,False,False,False,False,True,False,True,False,False,False
7,False,False,True,False,False,True,False,False,False,True,False,False
8,True,False,True,False,True,False,False,False,False,False,False,True
9,False,True,False,False,True,False,True,False,False,False,False,True

In [4]:
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
frequent_itemsets['lenght'] = frequent_itemsets['itemsets'].apply(lambda x:len(x))
rules1 = association_rules(frequent_itemsets, metric='lift', min_threshold=0.8)
rules1

ValueError: The input DataFrame `df` containing the frequent itemsets is empty.

In [12]:
frequent_itemsets

Empty DataFrame
Columns: [support, itemsets]
Index: []